name: Cypress Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false 
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cypress Run
        uses: cypress-io/github-action@v6.5.0
        with:
          record: true
          parallel: true
          ci-build-id: ${{ github.run_id }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
