name: Cypress Tests

on:
  push:
    branches:
      - main
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1, 2] # Uses 2 parallel instances
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Verify Cypress cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Run Cypress tests (record)
        run: npx cypress run --record --parallel --ci-build-id ${{ github.run_id }} --key ${{ secrets.CYPRESS_RECORD_KEY }}
